cloud:
  aws:
    region:
      static: us-east-1
      auto: false
    credentials:
      access-key: TESTE274775784A4784D
      secret-key: TESTE1274812787754477878
    end-point:
      uri: https://sqs.us-east-1.amazonaws.com/208471844409/guilherme-sqs